### ISSUE TITLE
api

### ISSUE THREAD

**Issue by barryblueice** [liyxii/suwingsHUB#1]
nonebot api：https://papi.barryblueice.top/api.php
调用示例：
![O~1T9)OFIALKLZF)49LF4W3](https://user-images.githubusercontent.com/44601454/210368432-5b2427d2-d71a-46e9-9d5b-a741ed89d143.png)

**Comment by alongw** [comment]
太慢了根本出不来，你放心我的suwingshub官方api马上就会出来

![image](https://user-images.githubusercontent.com/64565408/218301501-1027591e-8b32-4442-b8a7-c04708e24244.png)
